# coding=utf-8
# Copyright (c) 2026 Huawei Technologies Co., Ltd.
# This program is free software, you can redistribute it and/or modify it under the terms and conditions of
# CANN Open Software License Agreement Version 2.0 (the "License").
# Please refer to the License for details. You may not use this file except in compliance with the License.
# THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED,
# INCLUDING BUT NOT LIMITED TO NON-INFRINGEMENT, MERCHANTABILITY, OR FITNESS FOR A PARTICULAR PURPOSE.
# See LICENSE in the root of the software repository for the full text of the License.

"""PTO operation wrappers.

Every function in this module emits one or more MLIR operations at the
active insertion point and returns the primary SSA result(s).

Design rules:
- Vector math ops infer the result type from the first operand's type.
- ``vlds(tile[row, col:])`` and ``vlds(ptr, offset)`` infer the result
  ``vreg`` type from the source element type. ``vbrc_load`` still requires an
  explicit result ``vreg`` type because broadcast widths are authored
  explicitly in the current surface.
- ``make_tensor_view`` infers the TensorViewType from ``len(shape)`` and the
  pointer's element type.
- ``partition_view`` infers the PartitionTensorViewType from the source type."""

from functools import wraps
import warnings
from ._diagnostics import (
    PTODSLDeprecationWarning,
    explicit_mode_required_with_context_error,
    make_tensor_view_invalid_layout_error,
    make_tensor_view_missing_metadata_error,
    tile_row_alignment_error,
)
from ._host_tensors import resolve_tensor_data_entry
from ._scalar_coercion import coerce_scalar_to_type, materialize_scalar_literal
from ._scalar_adaptation import (
    classify_runtime_scalar_type,
    coerce_runtime_i1_value,
    coerce_runtime_index_value,
    coerce_runtime_integer_value,
)
from ._runtime_scalar_ops import emit_runtime_binary_op
from ._surface_values import (
    AllocatedBufferValue,
    MaskResultValue,
    PartitionTensorViewValue,
    TensorViewValue,
    TileSliceValue,
    TileValue,
    _coerce_index_value,
    _static_index_dims,
    _unwrap_sequence,
    compose_partition_spec,
    emit_as_ptr,
    infer_tile_element_type,
    is_runtime_scalar_ir_type,
    parse_tile_type_metadata,
    resolve_address_access,
    unwrap_surface_value,
    wrap_surface_value,
)
from ._types import (
    _is_struct_type,
    _isinstance_pto_type,
    _materialize_integer_literal,
    _normalize_address_space,
    _resolve,
    _strip_integer_signedness,
    mask_type,
    part_tensor_view_type,
    part_tensor_view_type_from_dims,
    ptr,
    tensor_view_type,
    tensor_view_type_from_dims,
    vreg_type,
)
from ptoas.mlir.dialects import arith, pto as _pto
from ptoas.mlir.ir import (
    Attribute,
    BF16Type,
    F16Type,
    F32Type,
    Float8E4M3FNType,
    Float8E5M2Type,
    FloatAttr,
    IndexType,
    IntegerAttr,
    IntegerType,
    MemRefType,
    Operation,
    Type,
    TypeAttr,
    UnitAttr,
    VectorType,
)

from ._ops_core import (  # noqa: F401
    _materialize_struct_value,
    _normalize_struct_path,
    _require_struct_value,
    _resolve_struct_path,
    const,
    declare_struct,
    get_op_attr,
    struct_get,
    struct_set,
)
from ._ops_common import (  # noqa: F401
    _CMP_MODE_TOKENS,
    _L1_CACHE_TOKENS,
    _LD_L2_CACHE_TOKENS,
    _MASK_PATTERN_TOKENS,
    _PIPE_ALIASES,
    _POST_UPDATE_TOKENS,
    _PREDICATE_LOAD_DIST_TOKENS,
    _PREDICATE_PART_TOKENS,
    _PREDICATE_STORE_DIST_TOKENS,
    _ROUNDING_TOKENS,
    _SATURATION_TOKENS,
    _SIGNEDNESS_TOKENS,
    _ST_L2_CACHE_CONTROL_VALUES,
    _ST_L2_CACHE_TOKENS,
    _TILE_MASK_PATTERN_TOKENS,
    _UNSET,
    _canonical_pipe_token,
    _cmp_mode_attr,
    _coerce_i1,
    _coerce_i32,
    _coerce_i32_operand,
    _coerce_i64,
    _coerce_index,
    _coerce_scalar_like_vector_element,
    _constant_like,
    _current_target_arch,
    _element_bytewidth,
    _elements_per_vreg,
    _emit_binary_vec_op,
    _emit_shift_vec_op,
    _emit_unary_vec_op,
    _emit_vec_scalar_masked_op,
    _enum_attr,
    _event_attr,
    _explicit_mode_only,
    _i64_zero,
    _index_zero,
    _infer_mask_metadata,
    _infer_vreg_metadata,
    _infer_vreg_type_from_address_source,
    _infer_vreg_type_from_tile_slice,
    _is_low_precision_elem_type,
    _l1_cache_attr,
    _ld_l2_cache_attr,
    _mask_bits_for_dtype,
    _mask_type_from_bits,
    _membar_attr,
    _mul_bytes,
    _negate_runtime_scalar,
    _normalize_acc_to_vec_mode,
    _normalize_cmp_mode,
    _normalize_enum_attr,
    _normalize_mask_pattern,
    _normalize_mte_store_l2_cache,
    _normalize_post_update_mode,
    _normalize_predicate_dist,
    _normalize_predicate_part,
    _normalize_sat_mode,
    _normalize_shift_count_vector,
    _normalize_tile_mask_pattern,
    _normalize_token,
    _normalize_vcvt_round_mode,
    _normalize_vdup_position_mode,
    _normalize_vpack_part,
    _optional_signedness_attr,
    _pipe_attr,
    _plt_op_for_mask_bits,
    _pointer_element_type,
    _pset_op_for_mask_bits,
    _reject_low_precision_vreg,
    _reject_low_precision_vreg_operands,
    _require_explicit_mode,
    _require_same_mask_types,
    _require_simt_subkernel,
    _require_target_arch,
    _required_signedness_attr,
    _resolve_mask_result_type,
    _resolve_precision_argument,
    _rounding_attr,
    _same_type_binary,
    _same_type_ternary,
    _same_type_unary,
    _saturation_attr,
    _simt_enum_attr,
    _st_l2_cache_attr,
    _surface_name_for_op_ctor,
    _tile_mask_pattern_attr,
    _tile_slice_address,
    _tile_slice_linear_offset,
    _tile_slice_ptr,
    _validate_convert_signedness,
    _validate_integer_signedness_only,
    _validate_raw_fill_l1_fill_word_bits,
    _validate_raw_fill_l1_static_scalar,
    _validate_redux_signedness,
    _validate_static_buf_id,
    _validate_static_event_id,
    _validate_static_event_id_range,
    _validate_sync_pipe,
    addptr,
    as_ptr,
    bytewidth,
    castptr,
    elements_per_vreg,
    init_align,
    vbitcast,
)
from ._ops_vmem import (  # noqa: F401
    _DEINTERLEAVE_DIST_TOKENS,
    _INTERLEAVE_DIST_TOKENS,
    _VCVT_BUILTIN_FLOAT_KINDS,
    _VCVT_CONTRACTS,
    _VCVT_ELEM_BITS,
    _VCVT_PTO_FLOAT_KINDS,
    _VLOAD_DIST_TOKENS,
    _VSTORE_DIST_TOKENS,
    _classify_vcvt_elem_kind,
    _classify_vcvt_integer_kind,
    _coerce_i16,
    _infer_result_vreg_type_for_element_dtype,
    _infer_vcvt_part_family,
    _infer_vpack_result_type,
    _normalize_dist_token,
    _normalize_vcvt_part_mode,
    _normalize_vcvt_sat_mode,
    _validate_vcvt_attrs,
    _validate_vcvt_dtype_pair,
    _vcvt_contract,
    _vector_memory_dist_kwargs,
    _vlds_pointer,
    _vlds_tile_slice,
    _vsts_pointer,
    _vsts_tile_slice,
    pbitcast,
    vcvt,
    vgather2,
    vgather2_bc,
    vgatherb,
    vldas,
    vlds,
    vldsx2,
    vldus,
    vmulscvt,
    vpack,
    vscatter,
    vsldb,
    vsstb,
    vsts,
    vstsx2,
)
from ._ops_mask import (  # noqa: F401
    _mask_pair_op,
    _pdintlv_op_for_mask_bits,
    _pge_impl,
    _pge_op_for_mask_bits,
    _pintlv_op_for_mask_bits,
    _plt_impl,
    _pset_impl,
    make_mask,
    pand,
    pdintlv_b16,
    pdintlv_b32,
    pdintlv_b8,
    pge_b16,
    pge_b32,
    pge_b8,
    pintlv_b16,
    pintlv_b32,
    pintlv_b8,
    plds,
    plt_b16,
    plt_b32,
    plt_b8,
    pnot,
    por,
    ppack,
    psel,
    pset_b16,
    pset_b32,
    pset_b8,
    psts,
    pstu,
    punpack,
    pxor,
    vcmp,
    vcmps,
    vstar,
    vstas,
    vstur,
    vstus,
)
from ._ops_vmath import (  # noqa: F401
    _coerce_vdup_scalar_input,
    _infer_vdup_scalar_result_type,
    _mask_granularity_bits,
    _resolve_l1_bypass_scalar_pointer,
    _validate_scalar_l1_bypass,
    chistv2,
    load_scalar,
    store_scalar,
    vabs,
    vadd,
    vaddc,
    vaddcs,
    vsubc,
    vsubcs,
    vaddrelu,
    vadds,
    vand,
    vands,
    vaxpy,
    vbitsort,
    vbr,
    vcadd,
    vcgadd,
    vcgmax,
    vcgmin,
    vci,
    vcmax,
    vcmin,
    vcpadd,
    vdintlv,
    vdiv,
    vdup,
    vexp,
    vexpdif,
    vintlv,
    vln,
    vlrelu,
    vmadd,
    vmax,
    vmaxs,
    vmin,
    vmins,
    vmrgsort4,
    vtranspose,
    vmul,
    vmula,
    vmull,
    vmuls,
    vneg,
    vnot,
    vor,
    vors,
    vprelu,
    vrec,
    vrelu,
    vrsqrt,
    vsel,
    vselr,
    vshl,
    vshls,
    vshr,
    vshrs,
    vsqrt,
    vsqz,
    vsub,
    vsubrelu,
    vsubs,
    vtrc,
    vxor,
    vxors,
)
from ._ops_tile import (  # noqa: F401
    _PRINT_FORMAT_ALIASES,
    _alloc_local_buffer,
    _authored_alloc_tile_type,
    _authored_tile_physical_shape,
    _coerce_tensor_view_layout_attr,
    _coerce_tile_scalar_operand,
    _emit_alloc_tile,
    _explicit_tile_valid_shape,
    _infer_tile_transfer_sizes,
    _is_partition_tensor_view,
    _is_persistent_alloc_buffer_candidate,
    _materialize_alloc_tile,
    _normalize_alloc_buffer_shape_metadata,
    _normalize_alloc_tile_request,
    _normalize_print_format,
    _normalize_static_tile_shape,
    _normalize_transfer_offsets,
    _normalize_transfer_sizes,
    _require_emitc_tprint_backend,
    _require_trandom_i32_scalar,
    _resolve_a5_mandatory_tmp,
    _resolve_selection_tmp,
    _source_view_rank,
    _split_valid_shape,
    _static_alloc_buffer_element_count,
    _tile_logical_rank,
    _tile_numel,
    _tile_transfer_partition,
    _unwrap_optional_integer,
    _uses_row_major_none_box_layout,
    _validate_authored_tile_row_alignment,
    _validate_tgather_mode,
    _wrap_allocated_tile,
    alloc_buffer,
    alloc_tile,
    make_tensor_view,
    partition_view,
    print,
    set_tile_valid_shape,
    tabs,
    tadd,
    taddrelu,
    tadds,
    tand,
    tands,
    tci,
    tcmp,
    tcmps,
    tcolargmax,
    tcolargmin,
    tcolexpand,
    tcolexpandadd,
    tcolexpanddiv,
    tcolexpandexpdif,
    tcolexpandmax,
    tcolexpandmin,
    tcolexpandmul,
    tcolexpandsub,
    tcolmax,
    tcolmin,
    tcolprod,
    tcolsum,
    tconcat,
    tcvt,
    tdequant,
    tdiv,
    tdivs,
    texp,
    texpands,
    textract,
    tfillpad,
    tfmod,
    tfmods,
    tgather,
    tgatherb,
    tgemv,
    tgemv_acc,
    tgemv_bias,
    tgemv_mx,
    tgemv_mx_acc,
    tgemv_mx_bias,
    tinsert,
    tload,
    tlog,
    tlrelu,
    tmatmul,
    tmatmul_acc,
    tmatmul_mx,
    tmatmul_mx_acc,
    tmatmul_mx_bias,
    tmax,
    tmaxs,
    tmin,
    tmins,
    tmov,
    tmrgsort,
    tmul,
    tmuls,
    tneg,
    tnot,
    tor,
    tors,
    tpartadd,
    tpartmax,
    tpartmin,
    tpartmul,
    tprelu,
    tprint,
    trandom,
    trecip,
    trelu,
    trem,
    trems,
    treshape,
    trowargmax,
    trowargmin,
    trowexpand,
    trowexpandadd,
    trowexpanddiv,
    trowexpandexpdif,
    trowexpandmax,
    trowexpandmin,
    trowexpandmul,
    trowexpandsub,
    trowmax,
    trowmin,
    trowprod,
    trowsum,
    trsqrt,
    tscatter,
    tsel,
    tsels,
    tshl,
    tshls,
    tshr,
    tshrs,
    tsort32,
    tsqrt,
    tstore,
    tsub,
    tsubs,
    tthistogram,
    ttrans,
    ttri,
    txor,
    txors,
)
from ._ops_mte import (  # noqa: F401
    _ACC_STORE_PRE_QUANT_MODES,
    _ACC_STORE_PRE_QUANT_SKIP_PAYLOAD_KIND_CHECK,
    _ACC_STORE_VECTOR_PRE_QUANT_MODES,
    _acc_store_atomic_attrs,
    _acc_store_layout,
    _acc_store_loop3,
    _acc_store_options,
    _acc_store_pre_quant,
    _acc_store_pre_relu,
    _acc_store_sat_attr,
    _acc_store_ub_dst_mode_attr,
    _acc_store_unit_flag_attr,
    _cube_load_frac_mode_attr,
    _infer_dma_2d_copy_signature,
    _infer_dma_partition_row_stride,
    _infer_dma_tile_geometry,
    _is_acc_store_float_scalar_payload,
    _is_acc_store_scaling_pointer_payload,
    _mad_mx_options,
    _mad_options,
    _mad_sat_attr,
    _mad_unit_flag_attr,
    _mte_l0c_ub_dst_mode,
    _normalize_cube_transpose,
    _normalize_dma_group,
    _normalize_dma_loops,
    _normalize_dma_pad,
    _normalize_frac_ctrl,
    _normalize_frac_dst_group,
    _normalize_frac_src_layout,
    _normalize_pair,
    _normalize_ub_split,
    _nullary_atomic_config,
    _require_pto_ptr_operand,
    _tf32_mode_attr,
    fill_tile,
    mad,
    mad_acc,
    mad_bias,
    mad_mx,
    mad_mx_acc,
    mad_mx_bias,
    mem_bar,
    mte_gm_l1,
    mte_gm_l1_frac,
    mte_gm_ub,
    mte_l0c_gm,
    mte_l0c_l1,
    mte_l0c_ub,
    mte_l1_bt,
    mte_l1_fb,
    mte_l1_l0a,
    mte_l1_l0a_mx,
    mte_l1_l0b,
    mte_l1_l0b_mx,
    mte_l1_ub,
    mte_load,
    mte_store,
    mte_ub_gm,
    mte_ub_l1,
    mte_ub_ub,
    raw_fill_l1,
    set_atomic_add,
    set_atomic_bf16,
    set_atomic_f16,
    set_atomic_f32,
    set_atomic_max,
    set_atomic_min,
    set_atomic_none,
    set_atomic_s16,
    set_atomic_s32,
    set_atomic_s8,
    set_store_atomic_cfg,
)
from ._ops_simt import (  # noqa: F401
    _atomic_binary,
    _buf_id_operand,
    _flag_event_id_operand,
    _slot_attr_value,
    _sync_event_id_operand,
    _sync_event_id_operand_in_range,
    _validate_shuffle_width,
    absf,
    atomic_add,
    atomic_and,
    atomic_cas,
    atomic_exch,
    atomic_max,
    atomic_min,
    atomic_or,
    atomic_sub,
    atomic_xor,
    ceil,
    convert,
    cos,
    exp,
    floor,
    fma,
    fmax,
    fmin,
    get_block_dim,
    get_block_dim_x,
    get_block_dim_y,
    get_block_dim_z,
    get_block_idx,
    get_block_idx_x,
    get_block_idx_y,
    get_block_idx_z,
    get_block_num,
    get_buf,
    get_clock32,
    get_clock64,
    get_grid_dim,
    get_grid_dim_x,
    get_grid_dim_y,
    get_grid_dim_z,
    get_laneid,
    get_lanemask_eq,
    get_lanemask_ge,
    get_lanemask_gt,
    get_lanemask_le,
    get_lanemask_lt,
    get_subblock_idx,
    get_subblock_num,
    get_tid,
    get_tid_x,
    get_tid_y,
    get_tid_z,
    get_veccoreid,
    import_reserved_buffer,
    keep,
    ldg,
    log,
    mul_i32toi64,
    mulhi,
    pipe_barrier,
    pow,
    prmt,
    redux_add,
    redux_max,
    redux_min,
    reserve_buffer,
    resume,
    rint,
    rls_buf,
    round,
    set_cross_block,
    set_flag,
    set_intra_block,
    shuffle_bfly,
    shuffle_down,
    shuffle_idx,
    shuffle_up,
    simt_launch,
    sin,
    sqrt,
    stg,
    store_vfsimt_info,
    syncthreads,
    threadfence,
    threadfence_block,
    trap,
    vote_all,
    vote_any,
    vote_ballot,
    vote_uni,
    wait_cross_block,
    wait_flag,
    wait_intra_block,
)

__all__ = [
    "const",
    "declare_struct", "struct_get", "struct_set",
    "castptr", "addptr",
    "vlds", "vldas", "vldus", "vldsx2", "vsts", "vstsx2",
    "init_align",
    "plt_b8", "plt_b16", "plt_b32",
    "pset_b8", "pset_b16", "pset_b32",
    "pge_b8", "pge_b16", "pge_b32",
    "make_mask",
    "pand", "por", "pxor", "pnot", "psel",
    "pbitcast", "vcvt", "vpack", "vmulscvt", "ppack", "punpack",
    "pintlv_b8", "pintlv_b16", "pintlv_b32",
    "pdintlv_b8", "pdintlv_b16", "pdintlv_b32",
    "vintlv", "vdintlv",
    "vgather2", "vgather2_bc", "vgatherb", "vscatter", "vsldb", "vsstb",
    "vcmp", "vcmps",
    "plds", "psts", "pstu", "vstar", "vstas", "vstur", "vstus",
    "vbitcast",
    "vbr",
    "vadd", "vsub", "vmul", "vdiv", "vmax", "vmin",
    "vaddc", "vaddcs", "vsubc", "vsubcs",
    "vtranspose",
    "vand", "vor", "vxor", "vshl", "vshr",
    "vcmax", "vcadd", "vcmin", "vdup", "vexpdif",
    "vexp", "vln", "vsqrt", "vabs", "vneg", "vrec", "vrsqrt", "vrelu", "vnot",
    "vcgmax", "vcgadd", "vcgmin", "vcpadd",
    "vadds", "vsubs", "vmuls", "vmaxs", "vmins", "vlrelu", "vshrs", "vshls", "vands", "vors", "vxors",
    "vaxpy", "vmula", "vci", "vaddrelu", "vsubrelu",
    "vsel",
    "make_tensor_view", "partition_view",
    "alloc_buffer", "alloc_tile",
    "tload", "tstore", "tmov", "tinsert", "tconcat",
    "tmatmul", "tmatmul_acc", "tmatmul_mx", "tmatmul_mx_acc", "tmatmul_mx_bias",
    "tgemv", "tgemv_acc", "tgemv_bias",
    "tgemv_mx", "tgemv_mx_acc", "tgemv_mx_bias",
    "tadd", "taddrelu", "tsub", "tmul", "tdiv", "tmax", "tmin",
    "trem", "trems", "tfmod", "tfmods",
    "tadds", "tsubs", "tmuls", "tdivs", "tmaxs", "tmins",
    "texp", "tlog", "tsqrt", "trsqrt", "trecip", "tabs", "tneg", "tdequant", "tprint", "print",
    "trelu", "tprelu", "tlrelu",
    "trandom",
    "trowsum", "trowmax", "trowmin", "trowprod", "trowargmax", "trowargmin",
    "tcolsum", "tcolmax", "tcolmin", "tcolprod", "tcolargmax", "tcolargmin",
    "tcmp", "tcmps",
    "texpands", "treshape", "trowexpand", "tcolexpand",
    "trowexpandadd", "trowexpandsub", "trowexpandmul", "trowexpanddiv", "trowexpandmax", "trowexpandmin", "trowexpandexpdif",
    "tcolexpandadd", "tcolexpandsub", "tcolexpandmul", "tcolexpanddiv", "tcolexpandmax", "tcolexpandmin", "tcolexpandexpdif",
    "tsort32", "tmrgsort", "tgather", "tscatter",
    "tsel", "tsels", "tcvt",
    "tnot", "tand", "tands", "tor", "tors", "txor", "txors", "tshl", "tshls", "tshr", "tshrs",
    "tpartadd", "tpartmul", "tpartmax", "tpartmin",
    "tfillpad",
    "ttri", "tthistogram",
    "chistv2",
    "as_ptr",
    "mte_load", "mte_store", "mte_gm_ub", "mte_ub_gm", "mte_ub_ub", "mte_ub_l1",
    "mte_gm_l1", "raw_fill_l1", "mte_l1_ub", "mte_gm_l1_frac", "mte_l1_bt", "mte_l1_fb", "mem_bar",
    "set_store_atomic_cfg",
    "set_atomic_add", "set_atomic_max", "set_atomic_min", "set_atomic_none",
    "set_atomic_f32", "set_atomic_f16", "set_atomic_bf16",
    "set_atomic_s32", "set_atomic_s16", "set_atomic_s8",
    "mte_l1_l0a", "mte_l1_l0b", "mte_l1_l0a_mx", "mte_l1_l0b_mx",
    "mte_l0c_l1", "mte_l0c_gm", "mte_l0c_ub",
    "mad", "mad_acc", "mad_bias", "mad_mx", "mad_mx_acc", "mad_mx_bias",
    "get_block_idx", "get_block_num", "get_subblock_idx", "get_subblock_num",
    "store_vfsimt_info", "simt_launch",
    "get_tid", "get_tid_x", "get_tid_y", "get_tid_z",
    "get_block_dim", "get_block_dim_x", "get_block_dim_y", "get_block_dim_z",
    "get_grid_dim", "get_grid_dim_x", "get_grid_dim_y", "get_grid_dim_z",
    "get_block_idx_x", "get_block_idx_y", "get_block_idx_z",
    "get_veccoreid", "get_clock32", "get_clock64",
    "get_laneid", "get_lanemask_eq", "get_lanemask_le", "get_lanemask_lt",
    "get_lanemask_ge", "get_lanemask_gt",
    "vote_all", "vote_any", "vote_uni", "vote_ballot",
    "shuffle_idx", "shuffle_up", "shuffle_down", "shuffle_bfly",
    "redux_add", "redux_max", "redux_min",
    "ldg", "stg",
    "atomic_exch", "atomic_add", "atomic_sub", "atomic_min", "atomic_max",
    "atomic_and", "atomic_or", "atomic_xor", "atomic_cas",
    "prmt", "mulhi", "mul_i32toi64",
    "absf", "sqrt", "exp", "log", "sin", "cos", "pow", "ceil", "floor", "rint", "round",
    "fmin", "fmax", "fma", "convert",
    "syncthreads", "threadfence", "threadfence_block", "trap", "keep", "resume",
    "pipe_barrier", "get_buf", "rls_buf",
    "set_cross_block", "wait_cross_block", "set_intra_block", "wait_intra_block",
    "set_flag", "wait_flag",
    "reserve_buffer", "import_reserved_buffer",
]
